# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      "usbhid"
    ];
    extraModulePackages = [ ];
    kernelModules = [
      "kvm-amd"
      "uinput"
      "wacom"
      "hid_wacom"
    ];
    kernelParams = [
      # "nvidia-drm.modeset=1"
      "quiet"
      "loglevel=0"
      "splash"
    ];

    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot = {
        enable = true;
        consoleMode = "max";
      };
    };

    plymouth = {
      enable = true;
    };

    kernel.sysctl = {
      "vm.overcommit_memory" = 2;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/864978b2-784f-4528-8aa0-b1d2b84e1e12";
    fsType = "ext4";
  };
  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/3F02C6C0060C36FF";
    fsType = "ntfs3";
    options = [
      "nofail"
      "x-systemd.automount"
    ];
  };
  fileSystems."/mnt/windows-ssd" = {
    device = "/dev/disk/by-uuid/524C612E40789B22";
    fsType = "ntfs3";
    options = [
      "nofail"
      "x-systemd.automount"
    ];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B442-5062";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 64000;
    } # size in MB, example = 8GB
  ];
  # zramSwap = {
  #   enable = true;
  #   memoryPercent = 50; # uses 50% of RAM as compressed swap
  # };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.config.allowUnfree = true;

  hardware = {
    uinput.enable = true;
    nvidia = {
      open = false;
      package = config.boot.kernelPackages.nvidiaPackages.beta;
      nvidiaSettings = true;
      videoAcceleration = true;
      modesetting.enable = true;
      gsp.enable = true;
    };
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opentabletdriver = {
      enable = true;
      daemon.enable = true;
    };
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        mesa
        wayland-protocols
      ];
    };
    bluetooth = {
      enable = true;
      powerOnBoot = true;
      settings = {
        Policy = {
          ReconnectAttempts = 20;
          ReconnectIntervals = "1,2,4,8";
        };
      };
    };
  };

  environment.variables = {
    XDG_SESSION_TYPE = "wayland";
    MOZ_ENABLE_WAYLAND = "1";
    NIXOS_OZONE_WL = "1";
    WLR_NO_HARDWARE_CURSORS = "1";
  };

  networking.firewall.allowedTCPPorts = [
    7860
    137
    138
    139
    445
  ];
}
